version: '3.8'

services:
  todo-application:
    image: todo-application-image:latest
    container_name: todo-app
    depends_on:
      - mysql-db
    networks:
      - todo-network
    ports:
      - "8082:8081"
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@123
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@123

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data: